import type { Metadata } from "next";
import "./globals.css";
import {
  instrumentSansItalic,
  instrumentSansRegular,
  instrumentSerifItalic,
  instrumentSerifRegular,
  tinosBold,
  tinosBoldItalic,
  tinosItalic,
  tinosRegular,
} from "@/fonts";
import Navigation from "@/components/navigation";
import Footer from "@/components/footer";
import ReactLenis from "lenis/react";

export const metadata: Metadata = {
  title: "Chambers of Zainul Rijal Firm",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactLenis root>
      <html lang="en">
        <body
          className={`${tinosRegular.variable} ${tinosItalic.variable} ${tinosBold.variable} ${tinosBoldItalic.variable} ${instrumentSerifItalic.variable} ${instrumentSerifRegular.variable} ${instrumentSansItalic.variable} ${instrumentSansRegular.variable} antialiased`}
        >
          <Navigation />
          <main>{children}</main>
          <Footer />
        </body>
      </html>
    </ReactLenis>
  );
}
